ALTER TABLE orders ADD COLUMN seller_id INTEGER REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE orders ADD COLUMN discount_type VARCHAR(10);
ALTER TABLE orders ADD COLUMN discount_value NUMERIC(12,2);
ALTER TABLE orders ADD COLUMN sale_channel_id INTEGER REFERENCES sale_channels(id) ON DELETE SET NULL;
ALTER TABLE orders DROP COLUMN IF EXISTS status;
ALTER TABLE orders DROP COLUMN IF EXISTS payment_status;
