GRANT USAGE ON SCHEMA public TO cristal;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO cristal;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO cristal;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO cristal;
